set(_CATKIN_CURRENT_PACKAGE "mecanum_robot_ver1")
set(mecanum_robot_ver1_VERSION "0.0.1")
set(mecanum_robot_ver1_MAINTAINER "MJU <dongilc@mju.ac.kr>")
set(mecanum_robot_ver1_PACKAGE_FORMAT "2")
set(mecanum_robot_ver1_BUILD_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_generation")
set(mecanum_robot_ver1_BUILD_EXPORT_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_generation")
set(mecanum_robot_ver1_BUILDTOOL_DEPENDS "catkin")
set(mecanum_robot_ver1_BUILDTOOL_EXPORT_DEPENDS )
set(mecanum_robot_ver1_EXEC_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_runtime")
set(mecanum_robot_ver1_RUN_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_runtime" "message_generation")
set(mecanum_robot_ver1_TEST_DEPENDS )
set(mecanum_robot_ver1_DOC_DEPENDS )
set(mecanum_robot_ver1_URL_WEBSITE "")
set(mecanum_robot_ver1_URL_BUGTRACKER "")
set(mecanum_robot_ver1_URL_REPOSITORY "")
set(mecanum_robot_ver1_DEPRECATED "")