set(_CATKIN_CURRENT_PACKAGE "kitech_robots_description")
set(kitech_robots_description_VERSION "0.0.0")
set(kitech_robots_description_MAINTAINER "Jungyeong Kim <kjy880527@gmail.com>, Jaehong Seo <jh_seo88@kitech.re.kr>")
set(kitech_robots_description_PACKAGE_FORMAT "1")
set(kitech_robots_description_BUILD_DEPENDS "rospy")
set(kitech_robots_description_BUILD_EXPORT_DEPENDS "rospy")
set(kitech_robots_description_BUILDTOOL_DEPENDS "catkin")
set(kitech_robots_description_BUILDTOOL_EXPORT_DEPENDS )
set(kitech_robots_description_EXEC_DEPENDS "rospy")
set(kitech_robots_description_RUN_DEPENDS "rospy")
set(kitech_robots_description_TEST_DEPENDS )
set(kitech_robots_description_DOC_DEPENDS )
set(kitech_robots_description_URL_WEBSITE "")
set(kitech_robots_description_URL_BUGTRACKER "")
set(kitech_robots_description_URL_REPOSITORY "")
set(kitech_robots_description_DEPRECATED "")