frequency: 20
sensor_timeout: 0.5
two_d_mode: false
print_diagnostics: true
publish_tf: true
publish_acceleration: true

map_frame: map
odom_frame: earth
base_link_frame: base_link
world_frame: earth
