set(_CATKIN_CURRENT_PACKAGE "kitech_robots_sims")
set(kitech_robots_sims_VERSION "0.0.0")
set(kitech_robots_sims_MAINTAINER "Jungyeong Kim <kjy880527@gmail.com>, Jaehong Seo <jh_seo88@kitech.re.kr>")
set(kitech_robots_sims_PACKAGE_FORMAT "1")
set(kitech_robots_sims_BUILD_DEPENDS "rospy")
set(kitech_robots_sims_BUILD_EXPORT_DEPENDS "rospy")
set(kitech_robots_sims_BUILDTOOL_DEPENDS "catkin")
set(kitech_robots_sims_BUILDTOOL_EXPORT_DEPENDS )
set(kitech_robots_sims_EXEC_DEPENDS "rospy")
set(kitech_robots_sims_RUN_DEPENDS "rospy")
set(kitech_robots_sims_TEST_DEPENDS )
set(kitech_robots_sims_DOC_DEPENDS )
set(kitech_robots_sims_URL_WEBSITE "")
set(kitech_robots_sims_URL_BUGTRACKER "")
set(kitech_robots_sims_URL_REPOSITORY "")
set(kitech_robots_sims_DEPRECATED "")