set(_CATKIN_CURRENT_PACKAGE "huboq_urdf_pkg")
set(huboq_urdf_pkg_VERSION "0.0.0")
set(huboq_urdf_pkg_MAINTAINER "cdi <cdi@todo.todo>")
set(huboq_urdf_pkg_PACKAGE_FORMAT "2")
set(huboq_urdf_pkg_BUILD_DEPENDS "geometry_msgs" "roscpp" "rviz" "tf" "urdf" "xacro")
set(huboq_urdf_pkg_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rviz" "tf" "urdf" "xacro")
set(huboq_urdf_pkg_BUILDTOOL_DEPENDS "catkin")
set(huboq_urdf_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(huboq_urdf_pkg_EXEC_DEPENDS "geometry_msgs" "roscpp" "rviz" "tf" "urdf" "xacro")
set(huboq_urdf_pkg_RUN_DEPENDS "geometry_msgs" "roscpp" "rviz" "tf" "urdf" "xacro")
set(huboq_urdf_pkg_TEST_DEPENDS )
set(huboq_urdf_pkg_DOC_DEPENDS )
set(huboq_urdf_pkg_URL_WEBSITE "")
set(huboq_urdf_pkg_URL_BUGTRACKER "")
set(huboq_urdf_pkg_URL_REPOSITORY "")
set(huboq_urdf_pkg_DEPRECATED "")