set(_CATKIN_CURRENT_PACKAGE "kitech_controllers")
set(kitech_controllers_VERSION "0.0.0")
set(kitech_controllers_MAINTAINER "Jungyeong Kim <kjy880527@gmail.com>, Jaehong Seo <jh_seo88@kitech.re.kr>")
set(kitech_controllers_PACKAGE_FORMAT "1")
set(kitech_controllers_BUILD_DEPENDS "controller_interface" "urdf" "control_msgs" "kdl_parser" "realtime_tools" "angles" "message_generation" "roscpp" "joy" "std_msgs")
set(kitech_controllers_BUILD_EXPORT_DEPENDS "controller_interface" "urdf" "control_msgs" "kdl_parser" "realtime_tools" "angles" "message_generation" "roscpp" "joy" "std_msgs")
set(kitech_controllers_BUILDTOOL_DEPENDS "catkin")
set(kitech_controllers_BUILDTOOL_EXPORT_DEPENDS )
set(kitech_controllers_EXEC_DEPENDS "controller_interface" "urdf" "control_msgs" "kdl_parser" "realtime_tools" "angles" "message_generation" "roscpp" "joy" "std_msgs")
set(kitech_controllers_RUN_DEPENDS "controller_interface" "urdf" "control_msgs" "kdl_parser" "realtime_tools" "angles" "message_generation" "roscpp" "joy" "std_msgs")
set(kitech_controllers_TEST_DEPENDS )
set(kitech_controllers_DOC_DEPENDS )
set(kitech_controllers_URL_WEBSITE "")
set(kitech_controllers_URL_BUGTRACKER "")
set(kitech_controllers_URL_REPOSITORY "")
set(kitech_controllers_DEPRECATED "")