# CMake generated Testfile for 
# Source directory: /home/cdi/Dropbox/Workspace_CDI/workspace_prog/catkin_ws/src
# Build directory: /home/cdi/Dropbox/Workspace_CDI/workspace_prog/catkin_ws/build-src-Desktop_Qt_5_12_9_GCC_64bit-RelWithDebInfo
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("gtest")
subdirs("kitech_legged_segway_robot_v0.2/kitech_legged_segway_robot/kitech_robots/kitech_robots_control")
subdirs("teleop_twist_keyboard")
subdirs("vesc/vesc")
subdirs("vesc/vesc_msgs")
subdirs("kitech_legged_segway_robot_v0.2/kitech_legged_segway_robot/kitech_robots/kitech_robots_description")
subdirs("kitech_legged_segway_robot_v0.2/kitech_legged_segway_robot/kitech_robots/kitech_robots_sims")
subdirs("qtros")
subdirs("razor_imu_9dof")
subdirs("amg_p1")
subdirs("differential_wheel_platform")
subdirs("huboq_remastered_test")
subdirs("huboq_remastered_ver1")
subdirs("huboq_ros/huboq_teleop")
subdirs("kitech_segway_type/kitech_segway_type_teleop")
subdirs("mecanum_robot_ver1")
subdirs("omniwheel_robot")
subdirs("tennis_ball_machine")
subdirs("two_link_planar_exp")
subdirs("kitech_legged_segway_robot_v0.2/kitech_legged_segway_robot/kitech_controllers")
subdirs("vesc/vesc_ackermann")
subdirs("vesc_control_ex1")
subdirs("vesc_control_ex2")
subdirs("vesc_control_ex3")
subdirs("vesc_control_ex4")
subdirs("vesc/vesc_driver")
subdirs("vrep_skeleton_msg_and_srv")
subdirs("vrep_plugin_imu")
subdirs("huboq_ros/huboq_urdf_pkg")
subdirs("kitech_segway_type/kitech_segway_urdf_pkg")
