set(_CATKIN_CURRENT_PACKAGE "vesc_control_ex3")
set(vesc_control_ex3_VERSION "0.0.1")
set(vesc_control_ex3_MAINTAINER "MJU <dongilc@mju.ac.kr>")
set(vesc_control_ex3_PACKAGE_FORMAT "2")
set(vesc_control_ex3_BUILD_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_generation")
set(vesc_control_ex3_BUILD_EXPORT_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_generation")
set(vesc_control_ex3_BUILDTOOL_DEPENDS "catkin")
set(vesc_control_ex3_BUILDTOOL_EXPORT_DEPENDS )
set(vesc_control_ex3_EXEC_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_runtime")
set(vesc_control_ex3_RUN_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_runtime" "message_generation")
set(vesc_control_ex3_TEST_DEPENDS )
set(vesc_control_ex3_DOC_DEPENDS )
set(vesc_control_ex3_URL_WEBSITE "")
set(vesc_control_ex3_URL_BUGTRACKER "")
set(vesc_control_ex3_URL_REPOSITORY "")
set(vesc_control_ex3_DEPRECATED "")