// Generated by gencpp from file amg_p1/CTM_Message.msg
// DO NOT EDIT!


#ifndef AMG_P1_MESSAGE_CTM_MESSAGE_H
#define AMG_P1_MESSAGE_CTM_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace amg_p1
{
template <class ContainerAllocator>
struct CTM_Message_
{
  typedef CTM_Message_<ContainerAllocator> Type;

  CTM_Message_()
    : stamp()
    , vel_target()
    , vel_now()
    , pos_target()
    , pos_now()
    , current()  {
    }
  CTM_Message_(const ContainerAllocator& _alloc)
    : stamp()
    , vel_target(_alloc)
    , vel_now(_alloc)
    , pos_target(_alloc)
    , pos_now(_alloc)
    , current(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _vel_target_type;
  _vel_target_type vel_target;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _vel_now_type;
  _vel_now_type vel_now;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pos_target_type;
  _pos_target_type pos_target;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pos_now_type;
  _pos_now_type pos_now;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _current_type;
  _current_type current;





  typedef boost::shared_ptr< ::amg_p1::CTM_Message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amg_p1::CTM_Message_<ContainerAllocator> const> ConstPtr;

}; // struct CTM_Message_

typedef ::amg_p1::CTM_Message_<std::allocator<void> > CTM_Message;

typedef boost::shared_ptr< ::amg_p1::CTM_Message > CTM_MessagePtr;
typedef boost::shared_ptr< ::amg_p1::CTM_Message const> CTM_MessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amg_p1::CTM_Message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amg_p1::CTM_Message_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amg_p1::CTM_Message_<ContainerAllocator1> & lhs, const ::amg_p1::CTM_Message_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.vel_target == rhs.vel_target &&
    lhs.vel_now == rhs.vel_now &&
    lhs.pos_target == rhs.pos_target &&
    lhs.pos_now == rhs.pos_now &&
    lhs.current == rhs.current;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amg_p1::CTM_Message_<ContainerAllocator1> & lhs, const ::amg_p1::CTM_Message_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amg_p1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::amg_p1::CTM_Message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amg_p1::CTM_Message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amg_p1::CTM_Message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amg_p1::CTM_Message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amg_p1::CTM_Message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amg_p1::CTM_Message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amg_p1::CTM_Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b224801613d8b47decc0b74376cfcb04";
  }

  static const char* value(const ::amg_p1::CTM_Message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb224801613d8b47dULL;
  static const uint64_t static_value2 = 0xecc0b74376cfcb04ULL;
};

template<class ContainerAllocator>
struct DataType< ::amg_p1::CTM_Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amg_p1/CTM_Message";
  }

  static const char* value(const ::amg_p1::CTM_Message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amg_p1::CTM_Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"float64[] vel_target\n"
"float64[] vel_now\n"
"float64[] pos_target\n"
"float64[] pos_now\n"
"float64[] current\n"
;
  }

  static const char* value(const ::amg_p1::CTM_Message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amg_p1::CTM_Message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.vel_target);
      stream.next(m.vel_now);
      stream.next(m.pos_target);
      stream.next(m.pos_now);
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CTM_Message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amg_p1::CTM_Message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amg_p1::CTM_Message_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "vel_target[]" << std::endl;
    for (size_t i = 0; i < v.vel_target.size(); ++i)
    {
      s << indent << "  vel_target[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.vel_target[i]);
    }
    s << indent << "vel_now[]" << std::endl;
    for (size_t i = 0; i < v.vel_now.size(); ++i)
    {
      s << indent << "  vel_now[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.vel_now[i]);
    }
    s << indent << "pos_target[]" << std::endl;
    for (size_t i = 0; i < v.pos_target.size(); ++i)
    {
      s << indent << "  pos_target[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pos_target[i]);
    }
    s << indent << "pos_now[]" << std::endl;
    for (size_t i = 0; i < v.pos_now.size(); ++i)
    {
      s << indent << "  pos_now[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pos_now[i]);
    }
    s << indent << "current[]" << std::endl;
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      s << indent << "  current[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.current[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMG_P1_MESSAGE_CTM_MESSAGE_H
