set(_CATKIN_CURRENT_PACKAGE "two_link_planar_exp")
set(two_link_planar_exp_VERSION "0.1.0")
set(two_link_planar_exp_MAINTAINER "cdi <cdi@gmail.com>")
set(two_link_planar_exp_PACKAGE_FORMAT "1")
set(two_link_planar_exp_BUILD_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(two_link_planar_exp_BUILD_EXPORT_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(two_link_planar_exp_BUILDTOOL_DEPENDS "catkin")
set(two_link_planar_exp_BUILDTOOL_EXPORT_DEPENDS )
set(two_link_planar_exp_EXEC_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(two_link_planar_exp_RUN_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(two_link_planar_exp_TEST_DEPENDS )
set(two_link_planar_exp_DOC_DEPENDS )
set(two_link_planar_exp_URL_WEBSITE "")
set(two_link_planar_exp_URL_BUGTRACKER "")
set(two_link_planar_exp_URL_REPOSITORY "")
set(two_link_planar_exp_DEPRECATED "")