set(_CATKIN_CURRENT_PACKAGE "kitech_segway_type_teleop")
set(kitech_segway_type_teleop_VERSION "0.0.1")
set(kitech_segway_type_teleop_MAINTAINER "MJU <dongilc@mju.ac.kr>")
set(kitech_segway_type_teleop_PACKAGE_FORMAT "2")
set(kitech_segway_type_teleop_BUILD_DEPENDS "joy" "roscpp" "std_msgs" "message_generation")
set(kitech_segway_type_teleop_BUILD_EXPORT_DEPENDS "joy" "roscpp" "std_msgs" "message_generation")
set(kitech_segway_type_teleop_BUILDTOOL_DEPENDS "catkin")
set(kitech_segway_type_teleop_BUILDTOOL_EXPORT_DEPENDS )
set(kitech_segway_type_teleop_EXEC_DEPENDS "joy" "roscpp" "std_msgs" "message_runtime")
set(kitech_segway_type_teleop_RUN_DEPENDS "joy" "roscpp" "std_msgs" "message_runtime" "message_generation")
set(kitech_segway_type_teleop_TEST_DEPENDS )
set(kitech_segway_type_teleop_DOC_DEPENDS )
set(kitech_segway_type_teleop_URL_WEBSITE "")
set(kitech_segway_type_teleop_URL_BUGTRACKER "")
set(kitech_segway_type_teleop_URL_REPOSITORY "")
set(kitech_segway_type_teleop_DEPRECATED "")