<?xml version="1.0"?>

<robot name="6dof_huboq" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Include materials -->

    <material name="Black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>

    <material name="Red">
        <color rgba="0.8 0.0 0.0 1.0"/>
    </material>

    <material name="White">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>


  <xacro:property name="deg_to_rad" value="0.01745329251994329577"/>


  <!-- Folder Setting -->
  <!-- small stl:huboq_mani_stl-small, original stl:huboq_mani_stl -->
  <xacro:property name="stl_folder" value="huboq_mani_stl-small"/>


  <!-- Constants -->
  <xacro:property name="M_SCALE" value="0.001 0.001 0.001"/> 
  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Link Properties -->
  <xacro:property name="mp_body_length" value="0.4" />
  <xacro:property name="mp_body_width" value="0.4" />
  <xacro:property name="mp_body_height" value="0.3" />

  <xacro:property name="mp_wheel_length" value="0.04" />
  <xacro:property name="mp_wheel_radius" value="0.19" />

  <xacro:property name="mani_offset_x" value="0"/>  <!-- 0.078" -->
  <xacro:property name="mani_offset_y" value="0."/>
  <xacro:property name="mani_offset_z" value="0"/>  <!-- 0.311" -->

  <xacro:property name="base_link_length" value="0.14" />
  <xacro:property name="base_link_width" value="0.07" />
  <xacro:property name="base_link_height" value="0.1" />

	<xacro:property name="HR_link_length" value="0.13" />
	<xacro:property name="HR_link_radius" value="0.06" />

	<xacro:property name="HP_link_length" value="0.1" />
	<xacro:property name="HP_link_width" value="0.11" />
  <xacro:property name="HP_link_height" value="0.28" />

	<xacro:property name="Knee_link_length" value="0.1" />
	<xacro:property name="Knee_link_width" value="0.11" />
  <xacro:property name="Knee_link_height" value="0.28" />

  <xacro:property name="AP_link_length" value="0.12" />
	<xacro:property name="AP_link_radius" value="0.06" />

	<xacro:property name="AR_link_length" value="0.15" />
	<xacro:property name="AR_link_width" value="0.10" />
  <xacro:property name="AR_link_height" value="0.175" />

  <xacro:property name="AY_link_length" value="0.4" />
	<xacro:property name="AY_link_width" value="0.35" />
  <xacro:property name="AY_link_height" value="0.18" />

  <!-- Inertia Properties -->
	<xacro:macro name="inertial_matrix" params="mass">
               <inertial>
                       <mass value="${mass}" />
                       <inertia ixx="0.5" ixy="0.0" ixz="0.0"
                                iyy="0.5" iyz="0.0"
                                izz="0.5" />
               </inertial>
	</xacro:macro>


  <!--     -->
   <xacro:macro name="transmission_block" params="joint_name">
	  <transmission name="tran1">
	    <type>transmission_interface/SimpleTransmission</type>
	    <joint name="${joint_name}">
	      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
	    </joint>
	    <actuator name="motor1">
	      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
	      <mechanicalReduction>1</mechanicalReduction>
	    </actuator>
	  </transmission>
   </xacro:macro>


  <!-- BASE-FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
  <link name="base_footprint">
    <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0" 
          izz="0.0001" />
    </inertial>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="mp_body" />
  </joint>

 <link name="mp_body">
    <visual>
      <geometry>
        <mesh filename="package://huboq_urdf_pkg/mesh/huboq_mp_stl-small/MP_Body.stl" scale="0.001 0.001 0.001"/>
      </geometry>
        <origin rpy="0 0 0" xyz="1.5 0.1155 0"/>
      <material name="green">
        <color rgba="0 0.7 0 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
	      <box size="${mp_body_length} ${mp_body_width} ${mp_body_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.2"/>
    </collision>

	  <xacro:inertial_matrix mass="1"/>
  </link>

  <gazebo reference="mp_body">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <link name="mp_left_caster">
    <visual>
      <geometry>
        <mesh filename="package://huboq_urdf_pkg/mesh/huboq_mp_stl-small/Caster_Blickle_Bracket_New.stl" scale="0.001 0.001 0.001"/>
      </geometry>
        <origin rpy="0 0 ${180*deg_to_rad}" xyz="0 0 0"/>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
	      <cylinder length="0.04" radius="0.03"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

	  <xacro:inertial_matrix mass="1"/>
  </link>

  <joint name="mp_left_caster_joint" type="continuous">
    <parent link="mp_body"/>
    <child link="mp_left_caster"/>
    <origin xyz="0.282 -0.17 0.135"/>
    <axis xyz="0 0 1" />
  </joint>


  <link name="mp_left_caster_wheel">
    <visual>
      <geometry>
        <mesh filename="package://huboq_urdf_pkg/mesh/huboq_mp_stl-small/Caster_Blickle_wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
        <origin rpy="${90*deg_to_rad} 0 0" xyz="0 0 0"/>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
	      <cylinder length="0.03" radius="0.05"/>
      </geometry>
      <origin rpy="${90*deg_to_rad} 0 0" xyz="0 -0.0155 0"/>
    </collision>

	  <xacro:inertial_matrix mass="1"/>
  </link>

  <joint name="mp_left_caster_wheel_joint" type="continuous">
    <parent link="mp_left_caster"/>
    <child link="mp_left_caster_wheel"/>
    <origin xyz="-0.038 0.0165 -0.085"/>
    <axis xyz="0 1 0" />
  </joint>


  
  <link name="mp_right_caster">
    <visual>
      <geometry>
        <mesh filename="package://huboq_urdf_pkg/mesh/huboq_mp_stl-small/Caster_Blickle_Bracket_New.stl" scale="0.001 0.001 0.001"/>
      </geometry>
        <origin rpy="0 0 ${180*deg_to_rad}" xyz="0 0 0"/>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
	      <cylinder length="0.04" radius="0.03"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

	  <xacro:inertial_matrix mass="1"/>
  </link>

  <joint name="mp_right_caster_joint" type="continuous">
    <parent link="mp_body"/>
    <child link="mp_right_caster"/>
    <origin xyz="0.282 0.17 0.135"/>
    <axis xyz="0 0 1" />
  </joint>


 <link name="mp_right_caster_wheel">
    <visual>
      <geometry>
        <mesh filename="package://huboq_urdf_pkg/mesh/huboq_mp_stl-small/Caster_Blickle_wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
        <origin rpy="${90*deg_to_rad} 0 0" xyz="0 0 0"/>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
	      <cylinder length="0.03" radius="0.05"/>
      </geometry>
      <origin rpy="${90*deg_to_rad} 0 0" xyz="0 -0.0155 0"/>
    </collision>

	  <xacro:inertial_matrix mass="1"/>
  </link>

  <joint name="mp_right_caster_wheel_joint" type="continuous">
    <parent link="mp_right_caster"/>
    <child link="mp_right_caster_wheel"/>
    <origin xyz="-0.038 0.0165 -0.085"/>
    <axis xyz="0 1 0" />
  </joint>


  <link name="mp_left_wheel">
    <visual>
      <geometry>
        <mesh filename="package://huboq_urdf_pkg/mesh/huboq_mp_stl-small/Wheel_Strida_16inch_Assy.stl" scale="0.001 0.001 0.001"/>
      </geometry>
        <origin rpy="${90.*M_PI/180.} 0 0" xyz="0.03 0 0"/>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
	      <cylinder length="${mp_wheel_length}" radius="${mp_wheel_radius}"/>
      </geometry>
      <origin rpy="${90.*M_PI/180.} 0 0" xyz="0 0.01 0"/>
    </collision>

	  <xacro:inertial_matrix mass="1"/>
  </link>

  <joint name="mp_left_wheel_joint" type="continuous">
    <parent link="mp_body"/>
    <child link="mp_left_wheel"/>
    <origin xyz="-0.078 0.232 0.19"/>
    <axis xyz="0 1 0" />
  </joint>

  <link name="mp_right_wheel">
    <visual>
      <geometry>
        <mesh filename="package://huboq_urdf_pkg/mesh/huboq_mp_stl-small/Wheel_Strida_16inch_Assy.stl" scale="0.001 0.001 0.001"/>
      </geometry>
        <origin rpy="${-90.*M_PI/180.} 0 0" xyz="0.03 0 0"/>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
	      <cylinder length="${mp_wheel_length}" radius="${mp_wheel_radius}"/>
      </geometry>
      <origin rpy="${-90.*M_PI/180.} 0 0" xyz="0 -0.01 0"/>
    </collision>

	  <xacro:inertial_matrix mass="1"/>
  </link>

  <joint name="mp_right_wheel_joint" type="continuous">
    <parent link="mp_body"/>
    <child link="mp_right_wheel"/>
    <origin xyz="-0.078 -0.232 0.19"/>
    <axis xyz="0 1 0" />
  </joint>


<!-- MANI -->
  <joint name="mp_mani_joint" type="fixed">
    <parent link="mp_body"/>
    <child link="base_link"/>
    <origin xyz="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
	      <mesh filename="package://huboq_urdf_pkg/mesh/${stl_folder}/base_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0.157 0 ${base_link_height/2+0.28}"/>
      <material name="yellow">
        <color rgba="1 1 0 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
	    <box size="${base_link_length} ${base_link_width} ${base_link_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0.09 0 ${base_link_height/2+0.31}"/>
    </collision>

	  <xacro:inertial_matrix mass="1"/>
  </link>

  <joint name="HR_joint" type="revolute">
    <parent link="base_link"/>
    <child link="HR_link"/>
    <origin xyz="${0.078} 0 ${0.41}"/>
    <axis xyz="1 0 0" />
    <limit effort="300" velocity="0.1" lower="${-40*deg_to_rad}" upper="${40*deg_to_rad}"/>
    <dynamics damping="50" friction="1"/>
  </joint>

  <link name="HR_link">
    <visual>
      <geometry>
	      <!-- <cylinder length="${HR_link_length}" radius="${HR_link_radius}"/> -->
        <mesh filename="package://huboq_urdf_pkg/mesh/${stl_folder}/hip_roll_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
        <!-- <origin rpy="0 ${90.*M_PI/180.} 0" xyz="0 0 0"/> -->
        <origin rpy="0 0 0" xyz="${0.707} 0.278 ${0.536}"/>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
	      <cylinder length="${HR_link_length}" radius="${HR_link_radius}"/>
      </geometry>
      <origin rpy="0 ${90.*M_PI/180.} 0" xyz="0 0 0"/>
    </collision>
	  <xacro:inertial_matrix mass="1"/>
  </link>

  <joint name="HP_joint" type="revolute">
    <parent link="HR_link"/>
    <child link="HP_link"/>
    <origin xyz="0 0 0"/>
    <axis xyz="0 1 0" />
    <limit effort="300" velocity="0.1" lower="${-80*deg_to_rad}" upper="${80*deg_to_rad}"/>
    <dynamics damping="50" friction="1"/>
  </joint>

  <link name="HP_link">
    <visual>
      <geometry>
        <!-- <box size="${HP_link_length} ${HP_link_width} ${HP_link_height}"/> -->
        <mesh filename="package://huboq_urdf_pkg/mesh/${stl_folder}/hip_pitch_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
        <!-- <origin rpy="0 0 0" xyz="0 0 ${HP_link_height/2}"/> -->
        <origin rpy="0 0 0" xyz="${1.4214} 0.115 ${-0.4095}"/>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
	      <box size="${HP_link_length} ${HP_link_width} ${HP_link_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${HP_link_height/2}"/>
    </collision>
  	<xacro:inertial_matrix mass="1"/>
  </link>

  <joint name="Knee_joint" type="revolute">
    <parent link="HP_link"/>
    <child link="Knee_link"/>
    <origin xyz="0 0 ${HP_link_height}"/>
    <axis xyz="0 1 0" />
    <limit effort="300" velocity="0.1" lower="${-160*deg_to_rad}" upper="${80*deg_to_rad}"/>
    <dynamics damping="50" friction="1"/>
  </joint>

  <link name="Knee_link">
    <visual>
      <geometry>
        <!--<box size="${Knee_link_length} ${Knee_link_width} ${Knee_link_height}"/> -->
        <mesh filename="package://huboq_urdf_pkg/mesh/${stl_folder}/knee_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
        <!-- <origin rpy="0 0 0" xyz="0 0 ${Knee_link_height/2}"/> -->
        <origin rpy="0 0 0" xyz="${0.0008} 0.0583 ${0.0005}"/>
      <material name="cyon">
        <color rgba="0 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
	      <box size="${Knee_link_length} ${Knee_link_width} ${Knee_link_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${Knee_link_height/2}"/>
    </collision>
  	<xacro:inertial_matrix mass="1"/>
  </link>

  <joint name="AP_joint" type="revolute">
    <parent link="Knee_link"/>
    <child link="AP_link"/>
    <origin xyz="0 0 ${Knee_link_height}"/>
    <axis xyz="0 1 0" />
    <limit effort="300" velocity="0.1" lower="${-90*deg_to_rad}" upper="${90*deg_to_rad}"/>
    <dynamics damping="50" friction="1"/>
  </joint>

  <link name="AP_link">
    <visual>
      <geometry>
	      <!-- <cylinder length="${AP_link_length}" radius="${AP_link_radius}"/> -->
        <mesh filename="package://huboq_urdf_pkg/mesh/${stl_folder}/ankle_pitch_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
        <!-- <origin rpy="${90.*M_PI/180.} 0 0" xyz="0 0 0"/> -->
        <origin rpy="0 0 0" xyz="${0.5709} 0.2673 ${0.222}"/>
      <material name="Magenta">
        <color rgba="1 0 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
	      <cylinder length="${AP_link_length}" radius="${AP_link_radius}"/>
      </geometry>
      <origin rpy="${90.*M_PI/180.} 0 0" xyz="0 0 0"/>
    </collision>
	  <xacro:inertial_matrix mass="1"/>
  </link>

  <joint name="AR_joint" type="revolute">
    <parent link="AP_link"/>
    <child link="AR_link"/>
    <origin xyz="0 0 0"/>
    <axis xyz="1 0 0" />
    <limit effort="300" velocity="0.1" lower="${-80*deg_to_rad}" upper="${80*deg_to_rad}"/>
    <dynamics damping="50" friction="1"/>
  </joint>

  <link name="AR_link">
    <visual>
      <geometry>
        <!-- <box size="${AR_link_length} ${AR_link_width} ${AR_link_height}"/> -->
        <mesh filename="package://huboq_urdf_pkg/mesh/${stl_folder}/ankle_roll_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
        <!-- <origin rpy="0 0 0" xyz="0 0 ${AR_link_height/2}"/> -->
        <origin rpy="0 0 0" xyz="${0.571} 0.2672 ${0.222}"/>
      <material name="orange">
        <color rgba="1 0.5 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
	      <box size="${AR_link_length} ${AR_link_width} ${AR_link_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${AR_link_height/2}"/>
    </collision>
  	<xacro:inertial_matrix mass="1"/>
  </link>

  <joint name="AY_joint" type="revolute">
    <parent link="AR_link"/>
    <child link="AY_link"/>
    <origin xyz="0 0 ${AR_link_height}"/>
    <axis xyz="0 0 1" />
    <limit effort="300" velocity="0.1" lower="-3.14" upper="3.14"/>
    <dynamics damping="50" friction="1"/>
  </joint>

  <link name="AY_link">
    <visual>
      <geometry>
	      <!-- <box size="${AY_link_length} ${AY_link_width} ${AY_link_height}"/>  -->
        <mesh filename="package://huboq_urdf_pkg/mesh/${stl_folder}/ankle_yaw_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
        <!-- <origin rpy="0 0 0" xyz="0 0 ${AY_link_height/2}"/> -->
        <origin rpy="0 0 0" xyz="${0.076} 0 ${-0.816}"/>
      <material name="Gray">
        <color rgba="0.3 0.3 0.3 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
	      <box size="${AY_link_length} ${AY_link_width} ${AY_link_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-0.028 0 ${AY_link_height/2}"/>
    </collision>
	  <xacro:inertial_matrix mass="1"/>
  </link>


  
<!-- ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->
  <!-- Transmissions for ROS Control -->

   <xacro:transmission_block joint_name="HR_joint"/>
   <xacro:transmission_block joint_name="HP_joint"/>
   <xacro:transmission_block joint_name="Knee_joint"/>
   <xacro:transmission_block joint_name="AP_joint"/>
   <xacro:transmission_block joint_name="AR_joint"/>
   <xacro:transmission_block joint_name="AY_joint"/>

 <!-- ros_control plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/6dof_huboq</robotNamespace>
    </plugin>
  </gazebo>



</robot>
