# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vesc_msgs/VescGetCustomApp.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class VescGetCustomApp(genpy.Message):
  _md5sum = "daa4967cc5ef43655bd186c327b3176d"
  _type = "vesc_msgs/VescGetCustomApp"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# VESCuino CDI CUSTOM_APP RX Messages

Header  header

# FW Version Data
int32 send_mode_index1
int32 fw_ver_major
int32 fw_ver_minor

# Original Get Value Data
#float64 voltage_input        # input voltage (volt)
#float64 temperature_pcb      # temperature of printed circuit board (degrees Celsius)
#float64 current_motor        # motor current (ampere)
#float64 current_input        # input current (ampere)
#float64 speed                # motor electrical speed (revolutions per minute) 
#float64 duty_cycle           # duty cycle (0 to 1)
#float64 charge_drawn         # electric charge drawn from input (ampere-hour)
#float64 charge_regen         # electric charge regenerated to input (ampere-hour)
#float64 energy_drawn         # energy drawn from input (watt-hour)
#float64 energy_regen         # energy regenerated to input (watt-hour)
#float64 displacement         # net tachometer (counts)
#float64 distance_traveled    # total tachnometer (counts)
int32   fault_code
#float64 pid_pos_now    		 # pid position now (deg) 0~360

int32 app_status_code        # application status code

# CAN Status Data 
int32 send_mode_index2
int32 can_devs_num
int32[] can_id
int32[] custom_status

# Raw Encoder Data
float64[] enc_rps		     # Encoder Read Raw Data (No Delay, rad/sec) 
float64[] enc_rad			 # Encoder Read Raw Data (No Delay, rad)
float64[] current			 # can status - current
float64[] duty			     # can status - duty

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','send_mode_index1','fw_ver_major','fw_ver_minor','fault_code','app_status_code','send_mode_index2','can_devs_num','can_id','custom_status','enc_rps','enc_rad','current','duty']
  _slot_types = ['std_msgs/Header','int32','int32','int32','int32','int32','int32','int32','int32[]','int32[]','float64[]','float64[]','float64[]','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,send_mode_index1,fw_ver_major,fw_ver_minor,fault_code,app_status_code,send_mode_index2,can_devs_num,can_id,custom_status,enc_rps,enc_rad,current,duty

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VescGetCustomApp, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.send_mode_index1 is None:
        self.send_mode_index1 = 0
      if self.fw_ver_major is None:
        self.fw_ver_major = 0
      if self.fw_ver_minor is None:
        self.fw_ver_minor = 0
      if self.fault_code is None:
        self.fault_code = 0
      if self.app_status_code is None:
        self.app_status_code = 0
      if self.send_mode_index2 is None:
        self.send_mode_index2 = 0
      if self.can_devs_num is None:
        self.can_devs_num = 0
      if self.can_id is None:
        self.can_id = []
      if self.custom_status is None:
        self.custom_status = []
      if self.enc_rps is None:
        self.enc_rps = []
      if self.enc_rad is None:
        self.enc_rad = []
      if self.current is None:
        self.current = []
      if self.duty is None:
        self.duty = []
    else:
      self.header = std_msgs.msg.Header()
      self.send_mode_index1 = 0
      self.fw_ver_major = 0
      self.fw_ver_minor = 0
      self.fault_code = 0
      self.app_status_code = 0
      self.send_mode_index2 = 0
      self.can_devs_num = 0
      self.can_id = []
      self.custom_status = []
      self.enc_rps = []
      self.enc_rad = []
      self.current = []
      self.duty = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7i().pack(_x.send_mode_index1, _x.fw_ver_major, _x.fw_ver_minor, _x.fault_code, _x.app_status_code, _x.send_mode_index2, _x.can_devs_num))
      length = len(self.can_id)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.pack(pattern, *self.can_id))
      length = len(self.custom_status)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.pack(pattern, *self.custom_status))
      length = len(self.enc_rps)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.enc_rps))
      length = len(self.enc_rad)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.enc_rad))
      length = len(self.current)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.current))
      length = len(self.duty)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.duty))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.send_mode_index1, _x.fw_ver_major, _x.fw_ver_minor, _x.fault_code, _x.app_status_code, _x.send_mode_index2, _x.can_devs_num,) = _get_struct_7i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.can_id = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.custom_status = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.enc_rps = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.enc_rad = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.current = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.duty = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7i().pack(_x.send_mode_index1, _x.fw_ver_major, _x.fw_ver_minor, _x.fault_code, _x.app_status_code, _x.send_mode_index2, _x.can_devs_num))
      length = len(self.can_id)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.can_id.tostring())
      length = len(self.custom_status)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.custom_status.tostring())
      length = len(self.enc_rps)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.enc_rps.tostring())
      length = len(self.enc_rad)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.enc_rad.tostring())
      length = len(self.current)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.current.tostring())
      length = len(self.duty)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.duty.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.send_mode_index1, _x.fw_ver_major, _x.fw_ver_minor, _x.fault_code, _x.app_status_code, _x.send_mode_index2, _x.can_devs_num,) = _get_struct_7i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.can_id = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.custom_status = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.enc_rps = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.enc_rad = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.current = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.duty = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7i = None
def _get_struct_7i():
    global _struct_7i
    if _struct_7i is None:
        _struct_7i = struct.Struct("<7i")
    return _struct_7i
