set(_CATKIN_CURRENT_PACKAGE "vesc_control_ex2")
set(vesc_control_ex2_VERSION "0.0.1")
set(vesc_control_ex2_MAINTAINER "MJU <dongilc@mju.ac.kr>")
set(vesc_control_ex2_PACKAGE_FORMAT "2")
set(vesc_control_ex2_BUILD_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_generation")
set(vesc_control_ex2_BUILD_EXPORT_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_generation")
set(vesc_control_ex2_BUILDTOOL_DEPENDS "catkin")
set(vesc_control_ex2_BUILDTOOL_EXPORT_DEPENDS )
set(vesc_control_ex2_EXEC_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_runtime")
set(vesc_control_ex2_RUN_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_runtime" "message_generation")
set(vesc_control_ex2_TEST_DEPENDS )
set(vesc_control_ex2_DOC_DEPENDS )
set(vesc_control_ex2_URL_WEBSITE "")
set(vesc_control_ex2_URL_BUGTRACKER "")
set(vesc_control_ex2_URL_REPOSITORY "")
set(vesc_control_ex2_DEPRECATED "")