(cl:in-package vesc_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SEND_MODE_INDEX1-VAL
          SEND_MODE_INDEX1
          FW_VER_MAJOR-VAL
          FW_VER_MAJOR
          FW_VER_MINOR-VAL
          FW_VER_MINOR
          FAULT_CODE-VAL
          FAULT_CODE
          APP_STATUS_CODE-VAL
          APP_STATUS_CODE
          SEND_MODE_INDEX2-VAL
          SEND_MODE_INDEX2
          CAN_DEVS_NUM-VAL
          CAN_DEVS_NUM
          CAN_ID-VAL
          CAN_ID
          CUSTOM_STATUS-VAL
          CUSTOM_STATUS
          ENC_RPS-VAL
          ENC_RPS
          ENC_RAD-VAL
          ENC_RAD
          CURRENT-VAL
          CURRENT
          DUTY-VAL
          DUTY
))