set(_CATKIN_CURRENT_PACKAGE "amg_p1")
set(amg_p1_VERSION "0.0.1")
set(amg_p1_MAINTAINER "naverlabs <dongil.choi@naverlabs.com>")
set(amg_p1_PACKAGE_FORMAT "2")
set(amg_p1_BUILD_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_generation")
set(amg_p1_BUILD_EXPORT_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_generation")
set(amg_p1_BUILDTOOL_DEPENDS "catkin")
set(amg_p1_BUILDTOOL_EXPORT_DEPENDS )
set(amg_p1_EXEC_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_runtime")
set(amg_p1_RUN_DEPENDS "joy" "roscpp" "std_msgs" "vesc_msgs" "message_runtime" "message_generation")
set(amg_p1_TEST_DEPENDS )
set(amg_p1_DOC_DEPENDS )
set(amg_p1_URL_WEBSITE "")
set(amg_p1_URL_BUGTRACKER "")
set(amg_p1_URL_REPOSITORY "")
set(amg_p1_DEPRECATED "")